apiVersion: v1
kind: Service
metadata:
  name: cups
  labels:
    app: cups
spec:
  ports:
  - name: "631"
    port: 631
    protocol: TCP
    targetPort: 631
  selector:
    app: cups
  type: ClusterIP
