apiVersion: v1
kind: Service
metadata:
  name: cups
  namespace: cups
  labels:
    app: cups
spec:
  ports:
  - name: cups
    port: 631
    protocol: TCP
    targetPort: 6631
  selector:
    app: cups
  type: ClusterIP
