apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cups
  namespace: cups
  labels:
    app: cups
spec:
  output:
    to:
      kind: ImageStreamTag
      name: cups:latest
  source:
    dockerfile: |
      FROM registry.redhat.io/ubi8-minimal
      COPY ./entrypoint /usr/bin
      COPY ./etc-pki-entitlement /etc/pki/entitlement
      COPY ./rhsm-conf /etc/rhsm
      COPY ./rhsm-ca /etc/rhsm/ca
      ENV CUPS_CONF=/etc/cups
      ENV CUPS_LOGS=/var/log/cups
      ENV CUPS_SPOOL=/var/spool/cups
      ENV CUPS_CACHE=/var/cache/cups
      ENV CUPS_RUN=/var/run

      RUN rm /etc/rhsm-host && \
        chmod 777 /usr/bin/entrypoint.sh && \
        microdnf install -y \
        --enablerepo=rhel-8-for-x86_64-appstream-rpms \
        --enablerepo=rhel-8-for-x86_64-baseos-rpms \
        cups \
        cups-client \
        hplip
      RUN mkdir -p ${CUPS_CACHE}
      RUN chgrp -R 0 ${CUPS_CONF} && \
          chgrp -R 0 ${CUPS_LOGS} && \
          chgrp -R 0 ${CUPS_SPOOL} && \
          chgrp -R 0 ${CUPS_CACHE} && \
          chgrp -R 0 ${CUPS_RUN} && \
          chmod -R g=u ${CUPS_CONF} && \
          chmod -R g=u ${CUPS_LOGS} && \
          chmod -R g=u ${CUPS_SPOOL} && \
          chmod -R g=u ${CUPS_CACHE} && \
          chmod -R g=u ${CUPS_RUN} && \
          chmod -R g=u /etc/passwd
      EXPOSE 6631
      USER 1001
      ENTRYPOINT ["/usr/bin/entrypoint.sh"]
    type: Dockerfile
    configMaps:
    - configMap:
        name: cups-entrypoint
      destinationDir: entrypoint
    - configMap:
        name: rhsm-conf
      destinationDir: rhsm-conf
    - configMap:
        name: rhsm-ca
      destinationDir: rhsm-ca
    secrets:
    - secret:
        name: etc-pki-entitlement
      destinationDir: etc-pki-entitlement
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
  - type: ConfigChange
